name = "sink"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "sink"

[vars]
NUXT_SITE_TOKEN = "SinkCool"

[[kv_namespaces]]
binding = "KV"
id = "17d4d405e13440f8b5a3379c6196f0d7"
